DROP TABLE IF EXISTS HISTORIQUE;
CREATE TABLE HISTORIQUE
(
    id             BIGINT PRIMARY KEY AUTO_INCREMENT,
    nombre         INT         NOT NULL,
    langue         VARCHAR(50) NOT NULL,
    date_recherche TIMESTAMP   NOT NULL
);